// <auto-generated />
using System;
using AspApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230226102545_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "TestPass1234",
                            Username = " hradmin@test.com"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 3,
                            Name = "dpmt1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 3,
                            Name = "dpmt2",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 4,
                            Name = "dpmt3",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 3,
                            Name = "dpmt5",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            ManagerId = 4,
                            Name = "dpmt6",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            ManagerId = 4,
                            Name = "dpmt7",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 8,
                            ManagerId = 10,
                            Name = "dpmt8",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            ManagerId = 11,
                            Name = "dpmt9",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 10,
                            ManagerId = 11,
                            Name = "dpmt10",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 11,
                            ManagerId = 11,
                            Name = "dpmt11",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 12,
                            ManagerId = 10,
                            Name = "dpmt12",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 13,
                            ManagerId = 10,
                            Name = "dpmt13",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 14,
                            ManagerId = 17,
                            Name = "dpmt14",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 15,
                            ManagerId = 17,
                            Name = "dpmt15",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 16,
                            ManagerId = 17,
                            Name = "dpmt16",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 17,
                            ManagerId = 18,
                            Name = "dpmt17",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 18,
                            ManagerId = 18,
                            Name = "dpmt18",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 19,
                            ManagerId = 18,
                            Name = "dpmt19",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManagerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "email1@ggmail.com",
                            FirstName = "Ketane",
                            IsManager = false,
                            LastName = "Maseloa",
                            ManagerId = 4,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 2,
                            Email = "email2@gmail.com",
                            FirstName = "Marks",
                            IsManager = false,
                            LastName = "Doe",
                            ManagerId = 3,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "email2@gmail.com",
                            FirstName = "Smith",
                            IsManager = true,
                            LastName = "Walker",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 4,
                            Email = "email3@gmail.com",
                            FirstName = "Lucky",
                            IsManager = true,
                            LastName = "Dube",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 5,
                            Email = "email4@gmail.com",
                            FirstName = "Raymond",
                            IsManager = false,
                            LastName = "Reddd",
                            ManagerId = 4,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 6,
                            Email = "email5@gmail.com",
                            FirstName = "David",
                            IsManager = false,
                            LastName = "Ricks",
                            ManagerId = 4,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 7,
                            Email = "email6@gmail.com",
                            FirstName = "Riri",
                            IsManager = false,
                            LastName = "Paris",
                            ManagerId = 10,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 8,
                            Email = "email1@ggmail.com",
                            FirstName = "Thandeka",
                            IsManager = false,
                            LastName = "Keeper",
                            ManagerId = 10,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 9,
                            Email = "email2@gmail.com",
                            FirstName = "Pro",
                            IsManager = false,
                            LastName = "Steve",
                            ManagerId = 10,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 10,
                            Email = "email2@gmail.com",
                            FirstName = "Smith",
                            IsManager = true,
                            LastName = "Walker",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 11,
                            Email = "email3@gmail.com",
                            FirstName = "Ompha",
                            IsManager = true,
                            LastName = "Fortunate",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 12,
                            Email = "email4@gmail.com",
                            FirstName = "Raymond",
                            IsManager = false,
                            LastName = "Reddd",
                            ManagerId = 11,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 13,
                            Email = "email5@gmail.com",
                            FirstName = "Milly",
                            IsManager = false,
                            LastName = "Thwala",
                            ManagerId = 11,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 14,
                            Email = "email6@gmail.com",
                            FirstName = "Selunathi",
                            IsManager = false,
                            LastName = "Muzex",
                            ManagerId = 17,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 15,
                            Email = "email1@ggmail.com",
                            FirstName = "Phindile",
                            IsManager = false,
                            LastName = "Sendisoa",
                            ManagerId = 17,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 16,
                            Email = "email2@gmail.com",
                            FirstName = "Mjeja",
                            IsManager = false,
                            LastName = "Revent",
                            ManagerId = 17,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 17,
                            Email = "email2@gmail.com",
                            FirstName = "Letor",
                            IsManager = true,
                            LastName = "Izzu",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 18,
                            Email = "email3@gmail.com",
                            FirstName = "Nikita",
                            IsManager = true,
                            LastName = "Dudu",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 19,
                            Email = "email4@gmail.com",
                            FirstName = "Phase",
                            IsManager = false,
                            LastName = "Way",
                            ManagerId = 18,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 20,
                            Email = "email5@gmail.com",
                            FirstName = "Rose",
                            IsManager = false,
                            LastName = "Pink",
                            ManagerId = 18,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 21,
                            Email = "email6@gmail.com",
                            FirstName = "Khanya",
                            IsManager = false,
                            LastName = "Phonm",
                            ManagerId = 18,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
