// <auto-generated />
using System;
using AspApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230225061256_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "TestPass1234",
                            Username = " hradmin@test.com"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 3,
                            Name = "department1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 3,
                            Name = "department2",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 4,
                            Name = "department3",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 3,
                            Name = "department5",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            ManagerId = 4,
                            Name = "department6",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 4,
                            Name = "department4",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManagerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "email1@ggmail.com",
                            FirstName = "Ketane",
                            IsManager = false,
                            LastName = "Maseloa",
                            ManagerId = 4,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 2,
                            Email = "email2@gmail.com",
                            FirstName = "Marks",
                            IsManager = false,
                            LastName = "Doe",
                            ManagerId = 3,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "email2@gmail.com",
                            FirstName = "Smith",
                            IsManager = true,
                            LastName = "Walker",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 4,
                            Email = "email3@gmail.com",
                            FirstName = "Lucky",
                            IsManager = true,
                            LastName = "Dube",
                            ManagerId = 0,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 5,
                            Email = "email4@gmail.com",
                            FirstName = "Raymond",
                            IsManager = false,
                            LastName = "Reddd",
                            ManagerId = 4,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 6,
                            Email = "email5@gmail.com",
                            FirstName = "David",
                            IsManager = false,
                            LastName = "Ricks",
                            ManagerId = 4,
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 7,
                            Email = "email6@gmail.com",
                            FirstName = "Riri",
                            IsManager = false,
                            LastName = "Paris",
                            ManagerId = 3,
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
