// <auto-generated />
using AspApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "TestPass1234",
                            Username = " hradmin@test.com"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 4,
                            Name = "dpmt1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 3,
                            Name = "dpmt2",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 10,
                            Name = "dpmt3",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 27,
                            Name = "dpmt5",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 11,
                            Name = "dpmt4",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "email1@ggmail.com",
                            FirstName = "Ketane",
                            IsManager = false,
                            LastName = "Maseloa",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "email2@gmail.com",
                            FirstName = "Marks",
                            IsManager = false,
                            LastName = "Doe",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "email2@gmail.com",
                            FirstName = "SmithE",
                            IsManager = true,
                            LastName = "WalkerMozi",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "email3@gmail.com",
                            FirstName = "Lucky",
                            IsManager = true,
                            LastName = "Dube",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Email = "email4@gmail.com",
                            FirstName = "Raymond",
                            IsManager = false,
                            LastName = "Reddd",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "email5@gmail.com",
                            FirstName = "David",
                            IsManager = false,
                            LastName = "Ricks",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            Email = "email6@gmail.com",
                            FirstName = "Riri",
                            IsManager = false,
                            LastName = "Paris",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            Email = "email1@ggmail.com",
                            FirstName = "Thandeka",
                            IsManager = false,
                            LastName = "Keeper",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Email = "email2@gmail.com",
                            FirstName = "Pro",
                            IsManager = false,
                            LastName = "Steve",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 3,
                            Email = "email2@gmail.com",
                            FirstName = "Smith",
                            IsManager = true,
                            LastName = "Walker",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 4,
                            Email = "email3@gmail.com",
                            FirstName = "Ompha",
                            IsManager = true,
                            LastName = "Fortunate",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 3,
                            Email = "email4@gmail.com",
                            FirstName = "Raymond",
                            IsManager = false,
                            LastName = "Reddd",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Email = "email5@gmail.com",
                            FirstName = "Milly",
                            IsManager = false,
                            LastName = "Thwala",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            Email = "email6@gmail.com",
                            FirstName = "Selunathi",
                            IsManager = false,
                            LastName = "Muzex",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 3,
                            Email = "email1@ggmail.com",
                            FirstName = "Phindile",
                            IsManager = false,
                            LastName = "Sendisoa",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 3,
                            Email = "email2@gmail.com",
                            FirstName = "Mjeja",
                            IsManager = false,
                            LastName = "Revent",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 4,
                            Email = "email2@gmail.com",
                            FirstName = "Letor",
                            IsManager = false,
                            LastName = "Izzu",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 4,
                            Email = "email3@gmail.com",
                            FirstName = "Nikita",
                            IsManager = false,
                            LastName = "Dudu",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 4,
                            Email = "email4@gmail.com",
                            FirstName = "Phase",
                            IsManager = false,
                            LastName = "Way",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 4,
                            Email = "email5@gmail.com",
                            FirstName = "Rose",
                            IsManager = false,
                            LastName = "Pink",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 4,
                            Email = "email6@gmail.com",
                            FirstName = "Khanya",
                            IsManager = false,
                            LastName = "Phonm",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 5,
                            Email = "email2@gmail.com",
                            FirstName = "Free",
                            IsManager = false,
                            LastName = "Mak",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 5,
                            Email = "email2@gmail.com",
                            FirstName = "Chance ",
                            IsManager = false,
                            LastName = "Bruno",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 5,
                            Email = "email3@gmail.com",
                            FirstName = "Tutu",
                            IsManager = false,
                            LastName = "Maplo",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 5,
                            Email = "email4@gmail.com",
                            FirstName = "Today",
                            IsManager = false,
                            LastName = "Santanda",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 5,
                            Email = "email5@gmail.com",
                            FirstName = "Acada",
                            IsManager = false,
                            LastName = "Spain",
                            Password = "Password123#",
                            Status = "Inactive",
                            Telephone = "4456789002"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 5,
                            Email = "email6@gmail.com",
                            FirstName = "Lindi",
                            IsManager = true,
                            LastName = "Phora",
                            Password = "Password123#",
                            Status = "Active",
                            Telephone = "4456789002"
                        });
                });

            modelBuilder.Entity("AspApp.Models.Employee", b =>
                {
                    b.HasOne("AspApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AspApp.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
